
# This document allows you to configure Save The World Daily
# https://github.com/dippyshere/stw-daily

# A list of error messages the bot can pick from for the error embeds.
error_messages = [
	"That wasn't supposed to happen",
	"Whoops!",
	"We hit a roadblock",
	"Not the llama you're looking for",
	"Uh-oh! Something goofed"
	]

support_url = "https://discord.gg/QYgABPDqzH"

# list of known auth codes which are automatically invalidated
known_auth_codes = [
	"ec684b8c687f479fadea3cb2ad83f5c6","3446cd72694c4a4485d81b77adbb2141","3f69e56c7649492c8cc29f1af08a8a12","efe3cbb938804c74b20e109d0efc1548",
	"cfaa14c4bf8744e3a5ef9a5d6c34558d","3e13c5c57f594a578abe516eecb673fe","5b685653b9904c1d92495ee8859dcb00","61d2f70175e84a6bba80a5089e597e1c",
	"FbiZv3wbiKpvVKrAeMxiR6WhxZWVbrvA","0716a69cb8b2422fbb2a8b0879501471","xyza7891343Fr4ZSPkQZ3kaL3I2sX8B5","34a02cf8f4414e29b15921876da36f9a",
	"38dbfc3196024d5980386a37b7c792bb","f3e80378aed4462498774a7951cd263f","1252412dc7704a9690f6ea4611bc81ee","ec813099a59f48d4a338f1901c1609db",
	"ad8def9ae6b84360b6c9b358aba06262","e0aca23dfb7348d6bad648bbe175a6e6","fa39ae1203b5438280f515f38a50f08e","9427129c087d4049886d3b47349d1aad",
	"b31a9e178ab84b21ad7435a53e4da4af","bc742d26f8314469aa997373f39c876e","875a3b57d3a640a6b7f9b4e883463ab4","cd2b7c19c9734a2ab98dc251868d7724",
	"4d9a4e9e568a40faa77b9757b4fac210","a472abd3e5ad4d90a0549213906dcf3f","7de9f4b799d3470984093b218287dc72","3cf78cd3b00b439a8755a878b160c7ad",
	"b070f20729f84693b5d621c904fc5bc2","f2f868d1259e4b128e5b7e8a3732cb1a","8f50327ba00d4ebeb81991ee04a42fc1","4b6c700c72c44e178b12070f2719af1a",
	"8df415b848c74affb682907405f7a52b","c4c02c7c99e94ed9870a9dbeafab2c3f","8e873617d81d4caf89bae28a4b74bbfe","43e2dea89b054198a703f6199bee6d5b",
	"24a1bff3f90749efbfcbc576c626a282","5a6fcd3b82e04f8fa0065253835c5221","f0b883ba7d3646bba4aa11bf1d71c071","1e2da690d4914a72a26be4d09862c559",
	"932e595bedb643d9ba56d3e1089a5c4b","8522af44af194836a532884e84d2b6e2","d7c956d5f1de46088dc2f5b8fccae940","8e889dadbfaf4145b3a806f51d1e3fee",
	"319e1527d0be4457a1067829fc0ad86e","0a4056c60cfd4e1f9f28795e529cd0c3","02612880aa774fb28e3741d3e01501fd","ba517836005c460eb18d368fa35eb002",
	"c1b81c9ba24e4b6ab3e99ad00320ffd2","9a06a69c0c8a458caab330d48badb877","0fa561666d6e41cb95b2a357a8b4a6f3","e7d1a3ee19ac4173b80a53006dc53be3",
	"189f729a313e415db0876a2091fecd8f","17ce2d2864834898ab71847859286c81","3adb22b897e24666971f9a273b1c15e8","f65082b48b504eb88f73961b0131cda7",
	"1412c33087cc452283d371665a8e5fbc","82f0e5faa90c4c209136870c50ae5642","1483ba7d6c0247828c26cc8a74a9a183","9fe4a9e4584c43a0bca6bd22a52f2f40",
	"a510a43d1fcc4636bc9c99a46a7cd50c","63f198487c8646f192a59be02ce0d14c","7f7b1f9ac72440408d65115cd49d0184","6ff43e743edc4d1dbac3594877b4bed9",
	"26c2c1eeeb9141a08d2e52afdda30fde","876dbf395577470794c0a43ca63abde4","d978d5ac4e1545d59e4e93a05ce77e26","8a438c1717d340429d5be1d6ce01f415",
	"74554a19f3674cb094a467237d174c16","xyza7891qtrmoYLr86we6DlfCA1RRsp8","72f83226ab664739b635b1e318a635bc"
	]

# permitted time for an auth session to run for (keep it below 5 hours)
auth_expire_time 	= 28800

# Names for the different shards
shard_names = [
	"Athena", "Apollo", "Artemis",
   "Demeter", "Zeus", "Hera",
   "Poseidon", "Ares", "Hephaestus",
   "Aphrodite", "Hermes", "Hestia",
   "Dionysus", "Hades", "Cronus",
   "Themis", "Rhea", "Hyperion",
   "Ouranos", "Helios", "Eos",
   "Prometheus", "Styx", "Atlas"
   ]

# a list of emojis the bot utilises throughout (please do not change the keys.)
[emojis]
info				= "<:helpstwdaily:925648230488883230>"
hard_drive  		= "<:TIconHardDriveL:812201309591175168>"
electric_plug		= "ðŸ”Œ"
research_point		= "<:TIconResearchPoint128:812201303781408828>"
error				= "<:errorstwdaily:925648230753107999>"
skill_point			= "<:TIconSkillPoint128:812201303505764373>"
warning				= "<:warningstwdaily:925648230736347158>"
vbucks				= "<:TItemsMTXL:812201307786969128>"
bulb				= "ðŸ’¡"
processing			= "<a:stwloading:947844940594044948>"
checkmark			= "<:checkmarkstwdaily:925648230912524338>"
founders			= "<:TIconFoundersBadge512:812201305736085524>"
calendar			= "<:TDestroyTheWorld:947752260295872532>"
blueinfo			= "<:infostwdaily:947807681404608532>"
xray				= "<:TItemsCurrencyXRayLlamaL:812201308286091264>"
keycard				= "<:ghostkeycard:956678535093813340>"
whitekey			= "<:librarykey:956794272412233730>"
llama				= "<:PinataStandardPack:947728062739542036>"
gold				= "<:TItemGoldBarsL:947728044448153611>"
stormeye			= "<:TItemsReagentCT03L:947728066984157214>"
bottlelightning 	= "<:TItemsReagentCT02L:947728059795120179>"
heroxp 				= "<:THeroXPL:947728056326422528>"
minillama_full		= "<:PinataMiniRewardPack:947728056334819328>"
minillama			= "<:TItemsVoucherBasicLrealesrganx4p:1028513525137674241>"
herogeneric			= "<:TIconHeroGeneric:947792566454210592>"
rangedgeneric		= "<:TIconRangedCARD:947728032045600788>"
meleegeneric		= "<:TIconMeleeCARD:947728031764611132>"
pdor				= "<:TItemsReagentCT01L:947728041596059718>"
freedoms_herald		= "<:TIconWeaponsSKFireCrackerGunL:947728057895125052>"
trapgeneric			= "<:TIconTrapsCARD:947728032813183076>"
defendergeneric 	= "<:TIconDefenders_CARD:947728018657390632>"
leadsurvivor		= "<:TIconSurvivorLeaderCARD:947728019450126356>"
xpboost				= "<:IconXPXL:812201307133313044>"
fortitude 			= "<:TIconFortitude:1000217972549357568>"
technology			= "<:TIconTech:1000217968560578600>"
offense 			= "<:TIconOffense:1000217970552877086>"
resistance 			= "<:TIconResistance:1000217966618615828>"
survivorgeneric		= "<:GenericWorkercopy:947728015683616778>"
teammatexpboost 	= "<:IconGiftXPXL:812201304670601227>"
crown 				= "ðŸ‘‘"
celebrate 			= "ðŸŽ‰"
stopwatch_anim		= "<a:stwstopwatch2:1028520039596445757>"
experimental		= "<:TBannersIconsBeakerLrealesrganx4:1028513516589682748>"
broken_heart		= "<:TBannersIconsLightningHeartLreal:1028513513364271145>"
vbuck_book			= "<:TIconVBuckChallengesLrealesrganx:1028513533366898748>"
storm_shield		= "<:TIconOutpost256realesrganx4plus:1028513536483274803>"
mtxswap_combined	= "<:TItemsCurrencyMTXXRayLlamaLreale:1028513530753847327>"
library_cal			= "<:T_UI_IconLibrary_Calendar_128rea:1028513523128614932>"
vbuck_icon			= "<:T_UI_icon_vbucks_128realesrganx4:1028828835002720286>"
stormshard			= "<:TItemsReagentCT04Lrealesrganx4pl:1028513528375689366>"
bp_icon				= "<:BPIcon:1028828256658534503>"
placeholder			= "<:T_UI_Challenge_MysteryRewardLrea:1028513520167428161>"
LMAO				= "ðŸ˜‚"
spongebob			= "<a:sadspongebob:1028829840977182770>"
megamind			= "<:megamind:1028829842776526868>"
cross				= "<:Cross:812201302041427969>"
right_icon			= "<:right_stw:1032194337783697419>"
left_icon			= "<:left_stw:1032194339398488064>"

#a list of links to thumbnails that the bot utilises for embeds
[thumbnails]
error				= "https://cdn.discordapp.com/attachments/748078936424185877/924999902851899452/errorstwdaily.png"
warn				= "https://cdn.discordapp.com/attachments/748078936424185877/924999901979508766/warningstwdaily.png?size=4096"
info				= "https://cdn.discordapp.com/attachments/748078936424185877/924999902612815892/infostwdaily.png"
help				= "https://cdn.discordapp.com/attachments/748078936424185877/924999902247936000/helpstwdaily.png"
check				= "https://cdn.discordapp.com/attachments/748078936424185877/924999903116165120/checkmarkstwdaily.png"
research			= "https://cdn.discordapp.com/attachments/767607876348018689/947812260724764712/T-Icon-ResearchPoint-128-realesrgan-x4plus.png"
processing			= "https://cdn.discordapp.com/attachments/767607876348018689/947999234169397248/stwloading.gif"
calendar			= "https://cdn.discordapp.com/attachments/767607876348018689/947752089549946930/Layer_4.png"
urlauthcode			= "https://cdn.discordapp.com/attachments/757768833946877992/874560824482623568/unknown.png?size=4096"
keycard				= "https://media.discordapp.net/attachments/643743040372080653/956798526149509120/Ghost_Keycard.PNG"
stormbottle 		= "https://media.discordapp.net/attachments/767607876348018689/947705710295261284/T-Items-Reagent-C-T02-L.png?width=410&height=410"
crown 				= "https://cdn.discordapp.com/attachments/643743040372080653/1000266990272913448/discordW_3.png"
placeholder			= "https://cdn.discordapp.com/attachments/643743040372080653/1028186514510839878/T_UI_Challenge_MysteryReward-L.png"
gold				= "https://cdn.discordapp.com/attachments/643743040372080653/1028186514976428032/T-Icon-S-Loot-GoldCurrency-L.png"
vbuck_book			= "https://cdn.discordapp.com/attachments/643743040372080653/1028186515773337640/T-Icon-VBuckChallenges-L.png"
daily_coin			= "https://cdn.discordapp.com/attachments/643743040372080653/1028186636900646942/T-Items-DailyCoin-L.png"
freedom_herald		= "https://cdn.discordapp.com/attachments/643743040372080653/1028186936613011456/WID_Pistol_FireCracker_R_Ore_T01.png"
clown				= "https://cdn.discordapp.com/attachments/917697167102206022/998935319313404004/20220719_224839.jpg"


# Different colours for commands
[colours]
generic_blue 		= [11, 123, 185]
error_red 			= [255,70,15]
warning_yellow 		= [252,224,44]
research_green 		= [114, 189, 134]
reward_magenta 		= [255, 0, 255]
success_green 		= [0, 210, 71]
auth_white      	= [255, 255 ,255]
crown_yellow		= [255, 204, 77]
vbuck_blue			= [99, 240, 238]

# Dont edit values beyond this point unless you know what you're doing!

# endpoints for requests to be sent to
[endpoints]
token 				= "https://account-public-service-prod.ol.epicgames.com/account/api/oauth/token"
profile 			= "https://fortnite-public-service-prod11.ol.epicgames.com/fortnite/api/game/v2/profile/{}/client/{}?profileId={}"
account 			= "https://account-public-service-prod.ol.epicgames.com/account/api/public/account/{}"
kill_token 			= "https://account-public-service-prod.ol.epicgames.com/account/api/oauth/sessions/kill/{}"
exchange 			= "https://account-public-service-prod.ol.epicgames.com/account/api/oauth/exchange"
device_auth 		= "https://account-public-service-prod.ol.epicgames.com/account/api/public/account/{}/deviceAuth"
store				= "https://fortnite-public-service-prod11.ol.epicgames.com/fortnite/api/storefront/v2/catalog"
news				= "https://fortnitecontent-website-prod07.ol.epicgames.com/content/api/pages/fortnite-game"
stw_news			= "https://fortnitecontent-website-prod07.ol.epicgames.com/content/api/pages/fortnite-game/savetheworldnews"
br_news				= "https://fortnite-api.com/v2/news/br"
pve_info			= "https://fortnite-public-service-prod11.ol.epicgames.com/fortnite/api/game/v2/world/info"

# different requests under profile
[profile]
query 				= "QueryProfile"
query_public 		= "QueryPublicProfile"
resources 			= "ClaimCollectedResources"
daily				= "ClaimLoginReward"
purchase_research 	= "PurchaseResearchStatUpgrade"
llamas				= "PopulatePrerolledOffers"
purchase			= "PurchaseCatalogEntry"
batch_recycle		= "RecycleItemBatch"
set_homebase		= "SetHomebaseName"
# thanks github?
set_banner			= "SetBanner"
set_banner_colour	= "SetBannerColor"
set_favourite		= "SetFavoriteHero"
set_favourite_loadout = "SetFavoriteLoadout"
set_favourite_schematic = "SetFavoriteSchematic"
set_favourite_survivor = "SetFavoriteSurvivor"
set_favourite_support = "SetFavoriteSupport"
set_favourite_trap 	= "SetFavoriteTrap"
set_favourite_weapon = "SetFavoriteWeapon"
set_favourite_backpack = "SetFavoriteBackpack"
set_favourite_pet 	= "SetFavoritePet"
set_favourite_pickaxe = "SetFavoritePickaxe"
set_favourite_glider = "SetFavoriteGlider"
set_favourite_emote = "SetFavoriteEmote"
set_favourite_skydive = "SetFavoriteSkydiveContrail"
set_favourite_musicpack = "SetFavoriteMusicPack"
set_favourite_loading = "SetFavoriteLoadingScreen"
set_favourite_battlebus = "SetFavoriteBattleBus"
set_favourite_battlepass = "SetFavoriteBattlePass"
set_favourite_battlepass_tier = "SetFavoriteBattlePassTier"
set_favourite_battlepass_star = "SetFavoriteBattlePassStar"
set_favourite_battlepass_star_tier = "SetFavoriteBattlePassStarTier"
set_favourite_battlepass_star_tier_reward = "SetFavoriteBattlePassStarTierReward"
set_favourite_battlepass_star_tier_reward_type = "SetFavoriteBattlePassStarTierRewardType"
set_favourite_battlepass_star_tier_reward_type_id = "SetFavoriteBattlePassStarTierRewardTypeId"
set_favourite_battlepass_star_tier_reward_type_id_name = "SetFavoriteBattlePassStarTierRewardTypeIdName"
set_favourite_battlepass_star_tier_reward_type_id_name_description = "SetFavoriteBattlePassStarTierRewardTypeIdNameDescription"
set_favourite_battlepass_star_tier_reward_type_id_name_description_image = "SetFavoriteBattlePassStarTierRewardTypeIdNameDescriptionImage"
set_favourite_battlepass_star_tier_reward_type_id_name_description_image_background = "SetFavoriteBattlePassStarTierRewardTypeIdNameDescriptionImageBackground"
set_favourite_battlepass_star_tier_reward_type_id_name_description_image_background_color = "SetFavoriteBattlePassStarTierRewardTypeIdNameDescriptionImageBackgroundColor"
set_favourite_battlepass_star_tier_reward_type_id_name_description_image_background_color_r = "SetFavoriteBattlePassStarTierRewardTypeIdNameDescriptionImageBackgroundColorR"
set_favourite_battlepass_star_tier_reward_type_id_name_description_image_background_color_g = "SetFavoriteBattlePassStarTierRewardTypeIdNameDescriptionImageBackgroundColorG"
set_favourite_battlepass_star_tier_reward_type_id_name_description_image_background_color_b = "SetFavoriteBattlePassStarTierRewardTypeIdNameDescriptionImageBackgroundColorB"
set_favourite_battlepass_star_tier_reward_type_id_name_description_image_background_color_a = "SetFavoriteBattlePassStarTierRewardTypeIdNameDescriptionImageBackgroundColorA"
set_favourite_battlepass_star_tier_reward_type_id_name_description_image_background_color_hex = "SetFavoriteBattlePassStarTierRewardTypeIdNameDescriptionImageBackgroundColorHex"
set_favourite_battlepass_star_tier_reward_type_id_name_description_image_background_color_hex_alpha = "SetFavoriteBattlePassStarTierRewardTypeIdNameDescriptionImageBackgroundColorHexAlpha"
set_favourite_battlepass_star_tier_reward_type_id_name_description_image_background_color_hex_alpha_value = "SetFavoriteBattlePassStarTierRewardTypeIdNameDescriptionImageBackgroundColorHexAlphaValue"
set_favourite_battlepass_star_tier_reward_type_id_name_description_image_background_color_hex_alpha_value_r = "SetFavoriteBattlePassStarTierRewardTypeIdNameDescriptionImageBackgroundColorHexAlphaValueR"
set_favourite_battlepass_star_tier_reward_type_id_name_description_image_background_color_hex_alpha_value_g = "SetFavoriteBattlePassStarTierRewardTypeIdNameDescriptionImageBackgroundColorHexAlphaValueG"
set_favourite_battlepass_star_tier_reward_type_id_name_description_image_background_color_hex_alpha_value_b = "SetFavoriteBattlePassStarTierRewardTypeIdNameDescriptionImageBackgroundColorHexAlphaValueB"
set_favourite_battlepass_star_tier_reward_type_id_name_description_image_background_color_hex_alpha_value_a = "SetFavoriteBattlePassStarTierRewardTypeIdNameDescriptionImageBackgroundColorHexAlphaValueA"
set_favourite_battlepass_star_tier_reward_type_id_name_description_image_background_color_hex_alpha_value_hex = "SetFavoriteBattlePassStarTierRewardTypeIdNameDescriptionImageBackgroundColorHexAlphaValueHex"
set_favourite_battlepass_star_tier_reward_type_id_name_description_image_background_color_hex_alpha_value_hex_alpha = "SetFavoriteBattlePassStarTierRewardTypeIdNameDescriptionImageBackgroundColorHexAlphaValueHexAlpha"
set_favourite_battlepass_star_tier_reward_type_id_name_description_image_background_color_hex_alpha_value_hex_alpha_value = "SetFavoriteBattlePassStarTierRewardTypeIdNameDescriptionImageBackgroundColorHexAlphaValueHexAlphaValue"
set_favourite_battlepass_star_tier_reward_type_id_name_description_image_background_color_hex_alpha_value_hex_alpha_value_r = "SetFavoriteBattlePassStarTierRewardTypeIdNameDescriptionImageBackgroundColorHexAlphaValueHexAlphaValueR"
set_favourite_battlepass_star_tier_reward_type_id_name_description_image_background_color_hex_alpha_value_hex_alpha_value_g = "SetFavoriteBattlePassStarTierRewardTypeIdNameDescriptionImageBackgroundColorHexAlphaValueHexAlphaValueG"
set_favourite_battlepass_star_tier_reward_type_id_name_description_image_background_color_hex_alpha_value_hex_alpha_value_b = "SetFavoriteBattlePassStarTierRewardTypeIdNameDescriptionImageBackgroundColorHexAlphaValueHexAlphaValueB"
set_favourite_battlepass_star_tier_reward_type_id_name_description_image_background_color_hex_alpha_value_hex_alpha_value_a = "SetFavoriteBattlePassStarTierRewardTypeIdNameDescriptionImageBackgroundColorHexAlphaValueHexAlphaValueA"
set_favourite_battlepass_star_tier_reward_type_id_name_description_image_background_color_hex_alpha_value_hex_alpha_value_hex = "SetFavoriteBattlePassStarTierRewardTypeIdNameDescriptionImageBackgroundColorHexAlphaValueHexAlphaValueHex"

# different profile ids under some endpoints
[profileid]
common_core			= "common_core"
common_public		= "common_public"
stw					= "campaign"
br					= "athena"
# i dont actually know if these are real github just suggested it
common_core_public	= "common_core_public"
campaign_missions	= "campaign_missions"
campaign_rewards	= "campaign_rewards"
collection_book		= "collection_book"
event_flags			= "event_flags"
event_rewards		= "event_rewards"
event_missions		= "event_missions"

[bannercolours]
defaultcolor1 		= "#545454"
defaultcolor2 		= "#c10000"
defaultcolor3 		= "#e44b00"
defaultcolor4 		= "#df7500"
defaultcolor5 		= "#ffbd00"
defaultcolor6 		= "#f7ce00"
defaultcolor7 		= "#f1df00"
defaultcolor8 		= "#bbe000"
defaultcolor9 		= "#91ed00"
defaultcolor10 		= "#00e28a"
defaultcolor11 		= "#00d6b3"
defaultcolor12 		= "#00f0f0"
defaultcolor13 		= "#00e8e8"
defaultcolor14 		= "#00bfe5"
defaultcolor15 		= "#00a3ff"
defaultcolor16 		= "#0000f8"
defaultcolor17 		= "#9300f0"
defaultcolor18 		= "#c800f0"
defaultcolor19 		= "#ed00ed"
defaultcolor20 		= "#f80098"
defaultcolor21 		= "#df0088"
defaultcolor22 		= "#191919"
defaultcolor23 		= "#4c0000"
defaultcolor24 		= "#5b2b00"
defaultcolor25 		= "#5c4400"
defaultcolor26 		= "#505d00"
defaultcolor27 		= "#395f00"
defaultcolor28 		= "#005b00"
defaultcolor29 		= "#005c4f"
defaultcolor30 		= "#003559"
defaultcolor31 		= "#000059"
defaultcolor32 		= "#3b0060"
defaultcolor33 		= "#50005d"
defaultcolor34 		= "#5f003a"
defaultcolor35 		= "#e0e0e0"
defaultcolor36 		= "#ff7f7f"
defaultcolor37 		= "#ffc766"
defaultcolor38 		= "#fff8a2"
defaultcolor39 		= "#cdff6e"
defaultcolor40 		= "#96ff96"
defaultcolor41 		= "#814bff"
defaultcolor42 		= "#9f9fff"
defaultcolor43 		= "#dba4ff"
defaultcolor44 		= "#ff97ff"